# Generated by Django 2.2.2 on 2019-07-08 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=1000)),
                ('Client', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Phone number')),
                ('born_date', models.DateField(blank=True, default=None, null=True, verbose_name='Born date')),
                ('last_connection', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date of last connection')),
                ('age', models.IntegerField(default=0, verbose_name='Age')),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasksmanager.UserProfile')),
            ],
            bases=('tasksmanager.userprofile',),
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasksmanager.UserProfile')),
                ('Specialisation', models.CharField(max_length=25)),
            ],
            bases=('tasksmanager.userprofile',),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=1000)),
                ('Time Elapsed', models.IntegerField(blank=True, default=None, null=True)),
                ('Importance', models.IntegerField()),
                ('Project', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasksmanager.Project')),
                ('UserProfile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasksmanager.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='DeveloperWorkTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time Elapsed', models.IntegerField(blank=True, default=None, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasksmanager.Task')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasksmanager.Developer')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='developers',
            field=models.ManyToManyField(related_name='developers', through='tasksmanager.DeveloperWorkTask', to='tasksmanager.Developer'),
        ),
        migrations.AddField(
            model_name='developer',
            name='Supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasksmanager.Supervisor'),
        ),
    ]
